import type { PointDefinition } from "../MapCalibration.entity";

export const hibiscusPoints: PointDefinition[] = [
  {
    markerId: "flor-hibisco-3",
    name: "Flor Hibisco",
    type: "hibiscus",
    iconId: "hibiscus",
    regionId: "Pais do Vento",
    subRegionId: "Oásis",
    timer: 600,
    x: 17.57,
    y: 76.57,
    description: "",
    layerIds: ["officialPins"],
  },
  {
    markerId: "flor-de-hibisco-8",
    name: "Flor de Hibisco",
    type: "hibiscus",
    iconId: "hibiscus",
    regionId: "Pais do Vento",
    subRegionId: "Oásis",
    timer: 600,
    x: 16.64,
    y: 76.68,
    description: "",
    layerIds: ["officialPins"],
  },
  {
    markerId: "flor-de-hibisco-10",
    name: "Flor de Hibisco",
    type: "hibiscus",
    iconId: "hibiscus",
    regionId: "Pais do Vento",
    subRegionId: "Oásis",
    timer: 600,
    x: 16.64,
    y: 76.03,
    description: "",
    layerIds: ["officialPins"],
  },
  {
    markerId: "flor-de-hibisco-13",
    name: "Flor de Hibisco",
    type: "hibiscus",
    iconId: "hibiscus",
    regionId: "Pais do Vento",
    subRegionId: "Oásis",
    timer: 600,
    x: 15.72,
    y: 75.42,
    description: "",
    layerIds: ["officialPins"],
  },
  {
    markerId: "flor-de-hibisco-14",
    name: "Flor de Hibisco",
    type: "hibiscus",
    iconId: "hibiscus",
    regionId: "Pais do Vento",
    subRegionId: "Oásis",
    timer: 600,
    x: 16.03,
    y: 75.39,
    description: "",
    layerIds: ["officialPins"],
  },
  {
    markerId: "flor-de-hibisco-19",
    name: "Flor de Hibisco",
    type: "hibiscus",
    iconId: "hibiscus",
    regionId: "Pais do Vento",
    subRegionId: "Oásis",
    timer: 600,
    x: 17.5,
    y: 73.86,
    description: "",
    layerIds: ["officialPins"],
  },
  {
    markerId: "flor-de-hibisco-20",
    name: "Flor de Hibisco",
    type: "hibiscus",
    iconId: "hibiscus",
    regionId: "Pais do Vento",
    subRegionId: "Oásis",
    timer: 600,
    x: 17.42,
    y: 72.84,
    description: "",
    layerIds: ["officialPins"],
  },
  {
    markerId: "flor-de-hibisco-25",
    name: "Flor de Hibisco",
    type: "hibiscus",
    iconId: "hibiscus",
    regionId: "Pais do Vento",
    subRegionId: "Oásis",
    timer: 600,
    x: 18.78,
    y: 73.72,
    description: "",
    layerIds: ["officialPins"],
  },
  {
    markerId: "flor-de-hibisco-28",
    name: "Flor de Hibisco",
    type: "hibiscus",
    iconId: "hibiscus",
    regionId: "Pais do Vento",
    subRegionId: "Oásis",
    timer: 600,
    x: 18.47,
    y: 74.45,
    description: "",
    layerIds: ["officialPins"],
  },
  {
    markerId: "flor-de-hibisco-29",
    name: "Flor de Hibisco",
    type: "hibiscus",
    iconId: "hibiscus",
    regionId: "Pais do Vento",
    subRegionId: "Oásis",
    timer: 600,
    x: 19.14,
    y: 74.72,
    description: "",
    layerIds: ["officialPins"],
  },
];
