import type { PointDefinition } from "../MapCalibration.entity";

export const orePoints: PointDefinition[] = [
  {
    markerId: "ore-1",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 46.29,
    y: 29.68,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-2",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 44.51,
    y: 29.1,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-3",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 46.33,
    y: 26.16,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-4",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 44.94,
    y: 25.13,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-5",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 46.71,
    y: 22.38,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-6",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 49.58,
    y: 23.71,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-7",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 49.77,
    y: 25.19,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-8",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 51.51,
    y: 26.32,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-9",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 50.42,
    y: 27.82,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-10",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 51.48,
    y: 28.74,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-11",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 53.35,
    y: 27.75,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-12",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 54.77,
    y: 26.67,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-13",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 53.1,
    y: 24.02,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-14",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 52.83,
    y: 21.64,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-15",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 50.8,
    y: 20.66,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-16",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 52.54,
    y: 18.99,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-17",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 56.15,
    y: 18.66,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-18",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 58.55,
    y: 19.31,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-19",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 60.45,
    y: 21.22,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-20",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 58.58,
    y: 21.73,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-21",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 56.8,
    y: 24.43,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-22",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 58.48,
    y: 25.17,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-23",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 57.44,
    y: 27.35,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-24",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 58.96,
    y: 28.24,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-25",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 60.32,
    y: 28.15,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-26",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 60.09,
    y: 26.88,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-27",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 62.54,
    y: 27.17,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-28",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 63.02,
    y: 27.75,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-29",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 61.68,
    y: 29.75,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-30",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 64.24,
    y: 30.89,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-31",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 64.7,
    y: 28.38,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-32",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 67.05,
    y: 26.81,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-33",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 68.41,
    y: 26.58,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-34",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 70.31,
    y: 25.68,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-35",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 69.92,
    y: 23.51,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-36",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 69.83,
    y: 20.48,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-37",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 66.72,
    y: 15.61,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-38",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 63.28,
    y: 14.75,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-39",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 61.22,
    y: 15.36,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-40",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 60.96,
    y: 18.43,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-41",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 62.31,
    y: 22.0,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-42",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 63.22,
    y: 23.24,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-43",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 63.83,
    y: 21.89,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-44",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 63.35,
    y: 20.68,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-45",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 62.35,
    y: 18.43,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-46",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 63.87,
    y: 17.9,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-47",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 65.73,
    y: 16.06,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-48",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 66.5,
    y: 16.46,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-49",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 66.3,
    y: 17.31,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-50",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 68.12,
    y: 17.56,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-51",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 68.21,
    y: 19.32,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-52",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 68.49,
    y: 21.26,
    description: "Mineração local",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-53",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 66.98,
    y: 21.8,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-54",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 65.72,
    y: 22.19,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-55",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 67.71,
    y: 23.89,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-56",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Tetsugakure",
    timer: 3600,
    x: 65.08,
    y: 24.65,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-57",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 48.5,
    y: 57.59,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-58",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 48.43,
    y: 57.12,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-59",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 47.48,
    y: 57.14,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-60",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 47.02,
    y: 56.73,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-61",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 45.79,
    y: 56.52,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-62",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 44.39,
    y: 56.79,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-63",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 44.56,
    y: 55.78,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-64",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 45.29,
    y: 55.64,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-65",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 47.03,
    y: 55.78,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-66",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 48.97,
    y: 55.17,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-67",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 47.99,
    y: 54.87,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-68",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 47.91,
    y: 53.57,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-69",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 46.06,
    y: 54.57,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-70",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 45.04,
    y: 54.03,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-71",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 44.68,
    y: 53.31,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-72",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 46.45,
    y: 51.62,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-73",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 44.93,
    y: 51.56,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-74",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 44.09,
    y: 50.95,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-75",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 46.0,
    y: 49.61,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-76",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 45.91,
    y: 48.47,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-77",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 46.79,
    y: 48.79,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-78",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 47.7,
    y: 48.33,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-79",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 46.35,
    y: 46.91,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-80",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 46.65,
    y: 46.96,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-81",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 48.22,
    y: 47.13,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-82",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 49.1,
    y: 48.12,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-83",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 48.74,
    y: 49.58,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-84",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 50.01,
    y: 49.68,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-85",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 50.81,
    y: 48.35,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-86",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 50.27,
    y: 47.26,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-87",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 52.09,
    y: 46.94,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-88",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 56.33,
    y: 48.22,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-89",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 56.43,
    y: 49.91,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-90",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 53.28,
    y: 50.84,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-91",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 52.87,
    y: 52.34,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-92",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 52.11,
    y: 53.6,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-93",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 51.89,
    y: 54.99,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-94",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Fogo",
    subRegionId: "Vale do Fim",
    timer: 3600,
    x: 50.55,
    y: 55.82,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-95",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 41.4,
    y: 32.87,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-96",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 41.38,
    y: 34.12,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-97",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 40.63,
    y: 36.48,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-98",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 38.96,
    y: 38.63,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-99",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 38.73,
    y: 42.03,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-100",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 35.88,
    y: 41.31,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-101",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 35.4,
    y: 42.38,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-102",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 36.78,
    y: 43.99,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-103",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 35.11,
    y: 46.82,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-104",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 33.96,
    y: 45.74,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-105",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 32.38,
    y: 48.21,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-106",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 30.45,
    y: 47.43,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-107",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 29.27,
    y: 47.93,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-108",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 28.24,
    y: 48.61,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-109",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 25.71,
    y: 49.25,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-110",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 26.22,
    y: 47.5,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-111",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 24.47,
    y: 46.67,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-112",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 25.3,
    y: 45.92,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-113",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 26.02,
    y: 43.28,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-114",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 24.93,
    y: 41.53,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-115",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 26.28,
    y: 39.56,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-116",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 25.76,
    y: 38.63,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-117",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 23.64,
    y: 39.81,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-118",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 22.95,
    y: 43.49,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-119",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 21.14,
    y: 42.56,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-120",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 21.14,
    y: 38.2,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-121",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 18.43,
    y: 39.59,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-122",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 17.34,
    y: 44.1,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-123",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 15.36,
    y: 42.06,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-124",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 12.28,
    y: 42.24,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-125",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 11.22,
    y: 40.67,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-126",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 13.8,
    y: 40.52,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-127",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 11.04,
    y: 37.45,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-128",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 15.04,
    y: 38.06,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-129",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 14.67,
    y: 35.95,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-130",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 16.71,
    y: 37.45,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-131",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 17.28,
    y: 36.56,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-132",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 19.27,
    y: 34.91,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-133",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 15.07,
    y: 33.91,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-134",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 11.3,
    y: 33.52,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-135",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 12.86,
    y: 30.91,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-136",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 17.08,
    y: 32.3,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-137",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 20.59,
    y: 31.19,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-138",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 19.15,
    y: 28.22,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-139",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 15.85,
    y: 28.12,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-140",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 15.39,
    y: 29.4,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-141",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 13.52,
    y: 28.37,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-142",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 13.11,
    y: 25.76,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-143",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 14.81,
    y: 24.36,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-144",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 15.5,
    y: 23.21,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-145",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 12.92,
    y: 22.78,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-146",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 15.14,
    y: 21.1,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-147",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 14.18,
    y: 20.09,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-148",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 17.47,
    y: 19.44,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-149",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 17.43,
    y: 20.62,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-150",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 18.87,
    y: 22.15,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-151",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 17.96,
    y: 24.67,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-152",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 19.3,
    y: 26.51,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-153",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 20.71,
    y: 26.39,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-154",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 21.46,
    y: 22.24,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-155",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 20.32,
    y: 19.39,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-156",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 24.39,
    y: 21.62,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-157",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 25.49,
    y: 24.49,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-158",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 23.19,
    y: 27.6,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-159",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 23.82,
    y: 30.17,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-160",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 26.37,
    y: 31.79,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-161",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 27.37,
    y: 29.1,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-162",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 28.97,
    y: 28.11,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-163",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 29.4,
    y: 24.58,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-164",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 26.87,
    y: 21.18,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-165",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 29.94,
    y: 22.35,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-166",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 30.79,
    y: 21.75,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-167",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 33.5,
    y: 20.78,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-168",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 35.95,
    y: 23.0,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-169",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 36.57,
    y: 26.25,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-170",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 32.32,
    y: 25.37,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-171",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 33.7,
    y: 27.43,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-172",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 32.64,
    y: 30.63,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-173",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 29.29,
    y: 32.23,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-174",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 28.97,
    y: 33.63,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-175",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 28.74,
    y: 35.79,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-176",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 28.67,
    y: 37.83,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-177",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 29.08,
    y: 38.67,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-178",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 28.58,
    y: 42.44,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-179",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 29.02,
    y: 44.39,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-180",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 31.09,
    y: 45.68,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-181",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 33.07,
    y: 43.44,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-182",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 31.37,
    y: 42.05,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-183",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 32.16,
    y: 39.76,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-184",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 31.09,
    y: 38.61,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-185",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 31.88,
    y: 36.07,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-186",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 31.99,
    y: 33.83,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-187",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 35.91,
    y: 31.11,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-188",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 34.53,
    y: 34.74,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-189",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 33.16,
    y: 37.87,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-190",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 34.91,
    y: 38.53,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-191",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 36.67,
    y: 37.3,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
  {
    markerId: "ore-192",
    name: "Minério",
    type: "ore",
    iconId: "ore_1",
    regionId: "Pais do Relâmpago",
    subRegionId: "Kumogakure",
    timer: 3600,
    x: 37.92,
    y: 33.92,
    description: "Local de mineração",
    layerIds: ["officialPins"],
  },
];
